# These variables define the project; they may not need to be changed
project:
  type: book
  output-dir: _book

# These variables define the book contents - adjust them as necessary
book:
  # [A] BOOK TITLE
  title: "BM327 Workshop 1: Seeking the Source of Hospital Infection"
  reader-mode: true
  
  # The cover image and favicon; these may not need to be changed
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  
  # Sets the page footer text/images
  # [B] FOOTER TEXT
  page-footer:
    left: |
      These BM327 workshop materials were written by Leighton Pritchard and Morgan Feeney
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  # Sets the URL for the repository
  # [C] GITHUB REPOSITORY URL
  repo-url: https://github.com/sipbs-compbiol/BM327_Workshop_1
  repo-branch: main
  repo-actions: [edit, issue]

  # Sets author information and publication/presentation date
  # [D] AUTHOR INFORMATION AND PUBLICATION/PRESENTATION DATE
  author: "Dr Leighton Pritchard and Dr Morgan Feeney"
  date: "21/02/25"

  # Define chapters and sections here
  # [E] CHAPTERS AND SECTIONS
  chapters:
    - index.qmd
    - intro.qmd
    - galaxy-registration.qmd
  
    - part: galaxy.qmd
      chapters: 
        - join-session.qmd
        - download-data.qmd
        - upload-data.qmd  

    - part: workshop.qmd
      chapters: 
        - fastqc.qmd
        - trimmomatic.qmd
        
    - part: mapping.qmd
      chapters:
        - bwamem.qmd

    - part: assembly.qmd
    
    - part: classification.qmd
    
    - part: phylogenetics.qmd

    - references.qmd

# Location of BibTeX format reference file; may not need to be changed
bibliography: references.bib

# Formatting and theme; may not need to be changed
format:
  html:
    theme: cosmo
    code-link: true
    
    author-meta: "Leighton Pritchard"
  
#  pdf:
#    documentclass: scrreprt

# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto
