# Preface to the {{< var ay >}} presentation {.unnumbered}

Welcome to the BM327 (Being a Biomolecular Scientist 3) bioinformatics workshop 1 for {{< var ay >}}.

This is the first presentation of this material, and we would be very grateful to hear feedback about it [by email](mailto:{{< var admin.email >}}) or through the [GitHub repository Issues page]({{< var github.issues >}}).

## Overview

This workshop asks you to carry out common bioinformatics analyses to trace the likely source of a _Pseudomonas aeruginosa_ infection in a hospital burns unit.
You will be using online bioinformatics services to do this.

::: { .callout-warning title="Important Note"}
There is new material in this workshop that is not covered in lectures, and **this material is examinable**. Please take care to read the text in the expandable callout boxes, as well as that for the workshop, to be sure you have understood the topic and obtain full value from the exercise.

The workshop material will remain live online for the duration of BM327, and you can revisit it whenever you wish, for practice or revision.
:::

**You should be able to complete this workshop in under two hours.**

## Learning Objectives

By the end of this workshop, students will be able to:

- Perform quality control on Illumina sequencing data
- Map Illumina-sequenced reads to a reference genome, to identify sequence variants
- Generate and annotate a phylogenetic tree
- Use genomic data to make an informed judgement about the likely source of a nosocomial infection

## Assessment

This workshop activity itself is not formally assessed although, as noted, all the material it contains is examinable. There is a formative assessment in the form of short answer questions [on MyPlace]({{< var myplace.url >}}), which you should complete as part of the workshop.
